// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Practico2.Data;
#nullable disable
namespace Practico2.Migrations
{
    [DbContext(typeof(EjemploDbContext))]
    [Migration("20240929190641_BD_Mejorada_VT")]
    partial class BD_Mejorada_VT
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.33")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);
            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);
            modelBuilder.Entity("Practico2.Models.Herramientas", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");
                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);
                b.Property<string>("Name")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");
                b.HasKey("Id");
                b.ToTable("Herramientas");
            });
            modelBuilder.Entity("Practico2.Models.Proyecto", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");
                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);
                b.Property<string>("Descripcion")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");
                b.Property<string>("Estado")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");
                b.Property<DateTime>("FechaCreacion")
                    .HasColumnType("datetime2");
                b.Property<int>("HorasTotales")
                    .HasColumnType("int");
                b.Property<int>("HorasTrabajadas")
                    .HasColumnType("int");
                b.Property<string>("Nombre")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");
                b.HasKey("Id");
                b.ToTable("Proyectos");
            });
            modelBuilder.Entity("Practico2.Models.Rol", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");
                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);
                b.Property<string>("Nombre")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");
                b.HasKey("Id");
                b.ToTable("Roles");
                b.HasData(
                    new
                    {
                        Id = 1,
                        Nombre = "Administrador"
                    },
                    new
                    {
                        Id = 2,
                        Nombre = "Empleado"
                    });
            });
            modelBuilder.Entity("Practico2.Models.Tarea", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");
                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);
                b.Property<string>("Area")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");
                b.Property<string>("EstadoTarea")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");
                b.Property<DateTime>("FechaInicio")
                    .HasColumnType("datetime2");
                b.Property<int>("Horas")
                    .HasColumnType("int");
                b.Property<int>("IdEmpleado")
                    .HasColumnType("int");
                b.Property<int>("IdProyecto")
                    .HasColumnType("int");
                b.HasKey("Id");
                b.ToTable("Tareas");
            });
            modelBuilder.Entity("Practico2.Models.Usuario", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");
                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);
                b.Property<string>("Apellido")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");
                b.Property<string>("Email")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");
                b.Property<string>("Nombre")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");
                b.Property<string>("Password")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");
                b.Property<int>("RolId")
                    .HasColumnType("int");
                b.HasKey("Id");
                b.ToTable("Usuarios");
                b.HasData(
                    new
                    {
                        Id = 1,
                        Apellido = "Perez",
                        Email = "juan@juan.cl",
                        Nombre = "Juan",
                        Password = "1234",
                        RolId = 1
                    },
                    new
                    {
                        Id = 2,
                        Apellido = "Perez",
                        Email = "pedro@pedro.cl",
                        Nombre = "Pedro",
                        Password = "1234",
                        RolId = 2
                    });
            });
#pragma warning restore 612, 618
        }
    }
}